### ISSUE TITLE
Move to newer JVM while still supporting 8

### ISSUE THREAD

**Issue by mathieucarbou** [mathieucarbou/license-maven-plugin#364]
> @mathieucarbou @dbwiddis Thoughts to dropping jdk 8 from the build? Newer java versions + extra enforcer rule for binaries is enough to ensure we remain properly java 8 compatible. Making that move will help with plugin items that are starting to drop jdk 8 support.

Yes that's something to do but in a more rigorous way because there are still some projects using 8 (or not able to use something else because of some external constraints). And a dev error is still possible if not properly checked, like using an API that is not available in 8.

I would even agree that we could switch by default to 17 **providing that we can:**

1) Either have some build jobs compiling with jvm 8 and running tests with jvm 8 (and only one dev branch)

2) Either have a `jdk8` branch with master on jvm 17 and we have this branch output artifacts in another version range, eventually with a classifier. This branch won't have any new features, just bug fixes. The main branch can be cleaned and we can use 9+ features.

Option 1) keeps one dev branch but is more messy for the build and infra stuff
Option 2) would have the cons of maintaining 2 branches, but we could do some cool cleanup on the main one on 17, and still keep the legacy jdk8

_Originally posted by @mathieucarbou in https://github.com/mathieucarbou/license-maven-plugin/issues/363#issuecomment-1108959234_

**Comment by mathieucarbou** [comment]
@dbwiddis @hazendaz : FYI created issue for discussing that ;-)

**Comment by dbwiddis** [comment]
Some general thoughts:
 - No need to move above 8 "just because". We should move to take advantage of some feature we want in the new version.  
 - We can retain JDK8 compatibility but just "build" on JDK11 to take advantage of checkstyle or any other plugin that requires JDK11.  Maven compiler plugin can enforce the JDK8 API easily.
 - Not sure we need to maintain (and keep up to date) a separate branch with a classifier.  I'd just keep the old JDK8 compatible version around as a 2.X branch, and do a major version bump for the new JDK version.  New features on the new version, backport bugfixes on the old 2.X branch.
 - We can isolate the JDK11 or JDK17 features in an optional dependency similar to how we currently offer git or svn for replacements.  That keeps the Mojo the same with JDK8 compatibility and some default features, but allows newer features.

**Comment by mathieucarbou** [comment]
> Some general thoughts:
> 
> * No need to move above 8 "just because". We should move to take advantage of some feature we want in the new version.

I agree 👍 

> * We can retain JDK8 compatibility but just "build" on JDK11 to take advantage of checkstyle or any other plugin that requires JDK11.  Maven compiler plugin can enforce the JDK8 API easily.

No need if we decide to switch main to 17 and keep 2.x for 8+ and only do bug fixes as needed: I don't see the point in upgrading but still limit what devs can do. Otherwise, if we want to keep main compatible with 11+, the let's switch to 11 for everything and not 17.

> * Not sure we need to maintain (and keep up to date) a separate branch with a classifier.  I'd just keep the old JDK8 compatible version around as a 2.X branch, and do a major version bump for the new JDK version.  New features on the new version, backport bugfixes on the old 2.X branch.

What I want too... We can branch when needed, in fact. I wouldn't even bother to port the new features back... Just do bug fixes.

> * We can isolate the JDK11 or JDK17 features in an optional dependency similar to how we currently offer git or svn for replacements.  That keeps the Mojo the same with JDK8 compatibility and some default features, but allows newer features.

That's an alternative option, yes, but not sure we need to go that far...

**Comment by hazendaz** [comment]
I think reading this we are +1 for using jdk 11 and cross compiling to jdk 8 for time being?  That is the easiest approach until we find some code reason otherwise ;)  I can work up the changes this coming weekend if we are ready for that.  It will be transparent to end user, we just need to note that in case others look at github actions to determine compatibility so noting on readme we are jdk 8+ (if not already would be a good move).

**Comment by hazendaz** [comment]
I'll work up to jdk 11 for this project while keeping jdk 8 compatibility.  We don't need to show we run on jdk 8.  Its well established at this point that is impossible to break it provided we use enforcer to ensure third party dependencies don't go up on us.  Its otherwise becoming really difficult to support that way and most major projects also flipped over in that regard for same reasons.  Its easy, will work on it this week so we can get checkstyle at least addressed if not other items in general for stability.

**Comment by mathieucarbou** [comment]
> I'll work up to jdk 11 for this project while keeping jdk 8 compatibility. We don't need to show we run on jdk 8. Its well established at this point that is impossible to break it provided we use enforcer to ensure third party dependencies don't go up on us. Its otherwise becoming really difficult to support that way and most major projects also flipped over in that regard for same reasons. Its easy, will work on it this week so we can get checkstyle at least addressed if not other items in general for stability.

I don't see the value, because it will add more complexity to the project compared to what it will bring, but I'm fine if it is done correctly. As long as we can still use the plugin in a project still based on 1.8. This implies changing a few things in the project and introduce toolchain maybe in order to:

1. compile and assemble with 11
2. keep 1.8 compat' (target option)
3. run all the unit tests and IT tests with several jvm versions: 1.8, 11 (and 17 if possible) => so add up as many GA matrix as necessary

1 year ago, 8 was still used a lot... More than 11. This is by far the version that is used the most. So my opinion on that is: unless we have a really good reason driven by a feature or blocker requiring us to switch to 11 or more, I really don't see why we should switch, and impact consuming projects, and add more burden in our development and CI.

Just maybe think about that and try analyse the complete set of required effort (toolchain, matrix build, different jvm, etc) and do the pros and cons ;-)

FYI. this is what we are doing at work, a lot of our consumers are on 1.8 and we have some matrix builds with toolchain. And this is also one of the reasons we cannot use the Findbugs maven plugin (it does not support toolchain), but I already explained you that ;-)

![](https://sdtimes.com/wp-content/uploads/2022/03/1bff659cc89d3a0080bba476624b7c9f.png)

**Comment by mathieucarbou** [comment]
closing since done, and now time also to drop 8.
