### ISSUE TITLE
Mandatory email in APACHE-2 template

### ISSUE THREAD

**Issue by scordio** [mathieucarbou/license-maven-plugin#532]
**Version affected**

4.1

**Describe the bug**

_I'm not sure this is a bug or it's by design so please accept my apologies if it's not the case._

Currently, the APACHE-2 [built-in template](https://github.com/mathieucarbou/license-maven-plugin/blob/master/license-maven-plugin/src/main/resources/com/mycila/maven/plugin/license/templates/APACHE-2.txt) requires a mandatory email value for the copyright line, producing an output like:

```
Copyright 2023 Owner Name (email@domain.com)

Licensed under the Apache License, Version 2.0 (the "License");
...
```

However, the header suggested by the APACHE-2 [license page](http://www.apache.org/licenses/LICENSE-2.0) only mentions:

```
Copyright [yyyy] [name of copyright owner]

Licensed under the Apache License, Version 2.0 (the "License");
...
```

without any explicit requirement for an email address in the copyright line.

If I don't specify the `email` property, I get a result like the following:

```
Copyright 2023 Owner Name (${email})

Licensed under the Apache License, Version 2.0 (the "License");
...
```

while I would like to get:

```
Copyright 2023 Owner Name

Licensed under the Apache License, Version 2.0 (the "License");
...
```

Aside from defining a custom header, I don't see any way to reach the result I'd like to have.

Would you consider some changes to achieve my last example with the built-in template? If yes, I can try to raise a PR.

**How to Reproduce**

Define:

```xml
        <configuration>
          <licenseSets>
            <licenseSet>
              <header>com/mycila/maven/plugin/license/templates/APACHE-2.txt</header>
              <includes>
                <include>src/**/*.java</include>
              </includes>
            </licenseSet>
          </licenseSets>
          <properties>
            <year>2023</year>
            <owner>Owner Name</owner>
          </properties>
        </configuration>
```

and execute `license:format`.

**Comment by hazendaz** [comment]
If you can send PR that keeps current behavior while making it possible to do the new behavior I think that we can accept.  I agree with your comments otherwise and while I don't use the templates any apache 2 I've done look as you have noted.

Personally I'm against emails there anyway for same reason I'm sure github does their best to hide ours.  Otherwise we get random inquires we don't ask for.  So definitely feel free to raise PR.  Looking forward to review.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Stefano Cordio ***@***.***>
Sent: Saturday, April 1, 2023 12:05:23 PM
To: mathieucarbou/license-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mathieucarbou/license-maven-plugin] Mandatory email in APACHE-2 template (Issue #532)


Version affected

4.1

Describe the bug

I'm not sure this is a bug or it's by design so please accept my apologies if it's not the case.

Currently, the APACHE-2 built-in template<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmathieucarbou%2Flicense-maven-plugin%2Fblob%2Fmaster%2Flicense-maven-plugin%2Fsrc%2Fmain%2Fresources%2Fcom%2Fmycila%2Fmaven%2Fplugin%2Flicense%2Ftemplates%2FAPACHE-2.txt&data=05%7C01%7C%7C43aab3e715044098e0a208db32cae6d1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638159619260618477%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ni%2BftIQ%2FNt38xMnIyt8vegrsvoQZPGAbSsswjAoHY%2Fw%3D&reserved=0> requires a mandatory email value for the copyright line, producing an output like:

Copyright 2023 Owner Name ***@***.***)

Licensed under the Apache License, Version 2.0 (the "License");
...


However, the header suggested by the APACHE-2 license page<https://na01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.apache.org%2Flicenses%2FLICENSE-2.0&data=05%7C01%7C%7C43aab3e715044098e0a208db32cae6d1%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638159619260618477%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=81pTb1MdRbie%2F5Wm%2B3bLHXpJJMxhHU9zjPBNkLkX5do%3D&reserved=0> only mentions:

Copyright [yyyy] [name of copyright owner]

Licensed under the Apache License, Version 2.0 (the "License");
...


without any explicit requirement for an email address in the copyright line.

If I don't specify the email property, I get a result like the following:

Copyright 2023 Owner Name (${email})

Licensed under the Apache License, Version 2.0 (the "License");
...


while I would like to get:

Copyright 2023 Owner Name

Licensed under the Apache License, Version 2.0 (the "License");
...


Aside from defining a custom header, I don't see any way to reach the result I'd like to have.

Would you consider some changes to achieve my last example with the built-in template? If yes, I can try to raise a PR.

How to Reproduce

Define:

        <configuration>
          <licenseSets>
            <licenseSet>
              <header>com/mycila/maven/plugin/license/templates/APACHE-2.txt</header>
              <includes>
                <include>src/**/*.java</include>
              </includes>
            </licenseSet>
          </licenseSets>
          <properties>
            <year>2023</year>
            <owner>Owner Name</owner>
          </properties>
        </configuration>

and execute license:format.

**Comment by scordio** [comment]
Hi @hazendaz, I started to look into this topic.

My idea would be to manipulate the string output after the properties are applied to the template, removing `(${email})` if there was no `email` property.

As far as I can see, there are no tests for the built-in templates and maybe I could start by adding them. I imagine the tests should belong to one of the classes in `com.mycila.maven.plugin.license.header` but I couldn't figure out the right candidate.

I'll take a deeper look over the next few days but I'm happy to follow your suggestions if you have any.

**Comment by hazendaz** [comment]
Keep this open.

**Comment by scordio** [comment]
Thanks @hazendaz and thanks `stale-bot` for the reminder 😅 

I'll try to come back to this topic in the coming weeks.

**Comment by scordio** [comment]
Yes, still relevant! 🙂

**Comment by dbwiddis** [comment]
Stale bot should have a way of marking something to not be reminded about again :)

**Comment by scordio** [comment]
Yes, still relevant! (Too late?)

**Comment by mathieucarbou** [comment]
@scordio : you will be able to point to `com/mycila/maven/plugin/license/templates/APACHE-2-noemail.txt` in next version.

**Comment by scordio** [comment]
Thanks a lot for taking care of it!
