### ISSUE TITLE
Support helm template comment style

### ISSUE THREAD

**Issue by jfallows** [mathieucarbou/license-maven-plugin#557]
**Describe the feature**

Helm chart templates use the following syntax for comments.
```
{{/*
...comment...
*/}}
```

We would like to be able to license check all of our helm chart source files, including any templates using the following configuration.
```
<configuration>
  <mapping>
    <tpl>HELM_TEMPLATE_STYLE</tpl>
  </mapping>
</configuration>
```

**Any alternative you've considered ?**

We tried the following but it did not work because mustache style is similar but still not valid syntax for helm chart template files.
```
<configuration>
  <mapping>
    <tpl>MUSTACHE_STYLE</tpl>
  </mapping>
</configuration>
```

**Comment by hazendaz** [comment]
Sounds reasonable. I'm not familiar with helm file types.  Could you write a pull with this feature or at least with some sample helm files I can work from?

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: John Fallows ***@***.***>
Sent: Sunday, May 14, 2023 11:57:19 AM
To: mathieucarbou/license-maven-plugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mathieucarbou/license-maven-plugin] Support helm template comment style (Issue #557)


Describe the feature

Helm chart templates use the following syntax for comments.

{{/*
...comment...
*/}}


We would like to be able to license check all of our helm chart source files, including any templates using the following configuration.

<configuration>
  <mapping>
    <tpl>HELM_TEMPLATE_STYLE</tpl>
  </mapping>
</configuration>


Any alternative you've considered ?

We tried the following but it did not work because mustache style is similar but still not valid syntax for helm chart template files.

<configuration>
  <mapping>
    <tpl>MUSTACHE_STYLE</tpl>
  </mapping>
</configuration>

**Comment by jfallows** [comment]
Note: we realized we can instead use `SCRIPT_STYLE` to also include the license comment in the `.yaml` generated from the template, which is a reasonable workaround versus not checking the license header for helm template files.
