### ISSUE TITLE
license files should support http and https license headers

### ISSUE THREAD

**Issue by hgschmie** [mathieucarbou/license-maven-plugin#585]
**Describe the feature**

A number of licenses (such as the apache license) is referred to by a URI. This currently is a http:// URI.

_A clear and concise description of what you want to happen._

I want to be able to use a https:// URI and the plugin should not flag this as "unexpected license header" but accept both http and https headers.

**Any alternative you've considered ?**

I could create a new license, APACHE2_HTTPS and use that. It seems clunky.

**Comment by hazendaz** [comment]
Thanks @hgschmie.  I agree this makes sense.  I've been switching over apache to https in various projects because it redirects there now.  So it would make sense to support both.  I presume you mean under the resources here for templates.  I'm not 100% up on that part of the project yet.  Bulk of my usage was to just apply them but was looking there last week and noticed we are missing many I'm sure.  I agree duplicating it doesn't make sense.

If you have time and have any idea on how to accomplish it easy enough, a PR would be welcome.  If not, I can try to look in coming weeks.  I have an ulterior motive on this project in general. Profiling shows its the worst of all plugins I use (well since I'm using the git module) so I've been trying to slowly upgrade this and fix as many things as possible.  As well as figure out some way of caching to some degree.  So knowing verification are hard-checking the http vs https is right up there.

@mathieucarbou Got any ideas roughly on this support feature?

**Comment by hgschmie** [comment]
well, easiest would be some kind of pattern matching support but this would slow down the plugin quite a bit. From what I see, there is some heuristics involved to match a header to a header definition. Maybe do all the work in the header definition (e.g. allow multiple lines that match, so one could provide two lines (one with http, one with https) as alternatives. 

Sorry, just spitballing here. I might think about a PR if I find time.

**Comment by dbwiddis** [comment]
This is on track with my original thoughts on #309.  

There's also a good argument for including SPDX identifiers, and none of the existing headers even offer that as an option to include.

I think the right answer is to have an overall template with a few "optional" areas where things can change (http or https, year of copyright, names of copyright holders, etc., an optional line adding SPDX, etc.) but the majority of the header is boilerplate.

Not sure the best way to do that but I think anything less really reduces the usefulness of this plugin.

**Comment by hazendaz** [comment]
keep open

**Comment by mathieucarbou** [comment]
> I want to be able to use a https:// URI and the plugin should not flag this as "unexpected license header" but accept both http and https headers.

I specifically didn't implement that in the plugin because a build has to be reproductible. If it depends on a remote call, any failure in grabbing the file with fail the build. And if you have to do a fix in a 1 year old branch, which points to an now inexisting URL, you don't have the content of the header file anymore.

**Comment by hgschmie** [comment]
I am not sure that I made my point clear. :-) 

The challenge is that there is a text block in a file that contains `http://.....`. This is part of the license header. 

There are code checkers that flag any `http://` URLs in source code as "unsafe", no matter where they are or what they mean. Corporate "security" scanners are a main culprit of this.

So a global "search and replace" command is run across the code base that replaces e.g. `http://www.apache.org/licenses/LICENSE-2.0` with `https://www.apache.org/licenses/LICENSE-2.0` in the license header. That's it. There is an additional `s`. 

Now the license plugin flags the license header as "unknown license" because it no longer matches character-for-character the license header that has been defined (either within the plugin itself or a policy jar on the plugin classpath). 

My current workaround is to have a second license block definition ("ASL_20_LICENSE_HTTPS") that is the same as e.g. the Apache 2.0 license, but the URL is a https url. This works fine, but feels clunky.

I am not sure how you arrived at "reproducible builds" and "remote calls" and "grabbing files". I proposed none of those things. All I want if we could find a way to make the plugin match `http://www.apache.org/licenses/LICENSE-2.0` and `https://www.apache.org/licenses/LICENSE-2.0` with the same template.

**Comment by mathieucarbou** [comment]
Changing some words in the license header changes the license.
There is no way to have the plugin interact with the inner content of each license to handle http/https links.
If the default license is not pleasing you can overwrite in the pol the license you want to be applied for a specific file extension.
You don't have to redefine a new license type.

**Comment by mathieucarbou** [comment]
Also, the current file header was selected according to Apache foundation instructions on how to add header:

https://www.apache.org/legal/apply-license.html#new

> Each original source document (code and documentation, but not the LICENSE and NOTICE files) should include a [short license header](https://www.apache.org/legal/src-headers.html#headers) at the top.

Link pointing to: https://www.apache.org/legal/src-headers.html#headers

An you will see that the content is http.

I am not a lawyer so I don't know about the implications of changing to an apache header form that is not the same as the recommended one (and I do not want this debate to happen).

The fact is that the plugin uses the header as instructed by the Apache foundation. 

Now, if you have a use case where you want to change the url scheme of all your license files just to please a security scan that you cannot configure or that is not smart enough to see it scanning a header, then this is up to you to change the header definition and all the files in your project.
